### ISSUE TITLE
beaulivre Theorem Error

### ISSUE THREAD

**Issue by Teddy-van-Jerry** [Jinwen-XU/colorist#3]
## Brief
I am now encountering a problem after updating `beaulivre` and `projlib` to the latest CTAN version (i.e. 0424).
I reckon this has something to do with the newly added **theorem** environment or their modification (Commits 5aeedfe96537a4e5b75df8b4c71f3292a36c220c, 8a52345ec08c1cfa6b38ac8bf55279ddde32273b, 27bae102e9eccf24b7bc7ea0ec07576dd76a4fb0, 455643fc174ec731fa303515f31688bdc9e2d375).
Due to my poor knowledge of expl3 and understanding of `projlib` package, I cannot figure out where the problem lies.

## Systems and Versions
- MacTeX 2022 on Mac Big Sur
- `beaulivre` 0424, `projlib` 0424

## Compiling Information
I am using LaTeXmk (XeLaTeX) to compile my document which has the class as
```tex
\documentclass[Chinese,TC,use boldface,simple name]{beaulivre} % the same result with `fast' option
```
Compile with options
```
latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdfxe
```
And with one of the errors
```
/usr/local/texlive/2022/texmf-dist/tex/latex/projlib/projlib-theorem.sty:167: Package create-theorem Error: The theorem-like environment "application"
(create-theorem)                cannot be created, you have to name it
(create-theorem)                before initialization.

Type <return> to continue.
 ...                                              
                                                  
l.167   }
```
In all, `application`, `claim`, `construction`, `recall`, `proposition-definition`, `theorem-definition` fail but I did not use these enviormnets in my document.

The complete log information is [here](https://pastebin.com/5QUgGq0A).

***
Thank you in advance!

**Comment by Jinwen-XU** [comment]
Thank you for the bug report. Unfortunately I cannot reproduce the error on my side, probably because I'm using the Github version which contains several changes not yet uploaded to CTAN (I've been busy preparing my exams recently, my apology).

From your log I'm not able to tell the version of the package `create-theorem` you are using. If after updating it to the currently newest version (2022-04-23) the issue remains, then please consider using the GitHub version of `projlib` and `beaulivre` as a temporary workaround. To my understanding the changes after  2022-04-24 are not related to this issue, so this is probably because `create-theorem` is not up-to-date.

P.S. I think you can drop the language options `Chinese,TC`. These options are originally designed because at the time the `originalref` mode of theorems was really slow and specifying the language with global option could save a lot of time. However, after several attempts of optimization (especially the birth of `create-theorem`) the performance issue has been resolved, thus these language options are not very useful for now. With this option given, `\UseLanguage{English}` will not be available and the line spacing might be too large if (occasionally) you wish to write English paragraphs in your book.

**Comment by Teddy-van-Jerry** [comment]
Now the problem is resolved after I update the `create-theorem` package. Thank you for your generous help!

Initially, I thought `create-theorem` is part of `projlib` so I did not realize it is a separate package. I am wondering if you could add `DEPENDS.txt` in the CTAN repo so that all these dependent packages will be updated automatically.
> This request is not that urgent so you might consider it after your exams. I also came here after I finished all the mid-term exams :-)
